version: '3.5'

services:
  mysql-server:
    image: mysql:5.7
    volumes:
      - $PWD/data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=my-password
      - MYSQL_DATABASE=wordpress_db
      - MYSQL_USER=wordpress_user 
      - MYSQL_PASSWORD=wordpress_passwd
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=mysql-server
    depends_on:
      - mysql-server
  wordpress:
    image: wordpress:5.4
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - mysql-server