version: '3'

services:
  mongo:
    image: mongo:latest
    volumes:
     - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  mongo-express:
    image: mongo-express:latest
    restart: always
    environment:
     - ME_CONFIG_MONGODB_SERVER=mongo
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
    ports:
      - '8081:8081'
    depends_on:
      - mongo